const ADDTOCART = "ADDTOCART";
const DECREASEFROMCART = "DECREASEFROMCART";
const INCREASEFROMCART = "INCREASEFROMCART";
const REMOVEITEM = "REMOVEITEM";

export { ADDTOCART, DECREASEFROMCART, INCREASEFROMCART, REMOVEITEM };
